name: ghorer_bazar_app
description: A comprehensive e-commerce app for Ghorer Bazar with Supabase, Sembast, and Riverpod

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Backend & Database
  supabase_flutter: ^2.0.0
  sembast: ^3.4.9
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # UI & Images
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  badges: ^3.1.2
  shimmer: ^3.0.0
  
  # Networking & JSON
  http: ^1.1.0
  json_annotation: ^4.8.1
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  flutter_dotenv: ^5.1.0
  
  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env
      
